version: "3.5"

services:
  api:
    build: .
    hostname: api
    ports:
     - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "1.33"
          memory: "540MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"